/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowRight: typeof import('./src/components/icon/arrow-right.vue')['default']
    Brand: typeof import('./src/components/icon/brand.vue')['default']
    Bubble: typeof import('./src/components/message/bubble.vue')['default']
    Card: typeof import('./src/components/card/card.vue')['default']
    Card2: typeof import('./src/components/card/card-2.vue')['default']
    Checkbox1: typeof import('./src/components/checkbox/checkbox-1.vue')['default']
    CircleProgress: typeof import('./src/components/progress/circle-progress.vue')['default']
    ContextMenuInner: typeof import('./src/components/context-menu/context-menu-inner.vue')['default']
    ContextMenuOuter: typeof import('./src/components/context-menu/context-menu-outer.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/header/header.vue')['default']
    InstanceCard: typeof import('./src/components/card/instance-card.vue')['default']
    LeftMenu: typeof import('./src/components/menu/left-menu.vue')['default']
    Loading1: typeof import('./src/components/loading/loading-1.vue')['default']
    Loading2: typeof import('./src/components/loading/loading-2.vue')['default']
    Loading3: typeof import('./src/components/loading/loading-3.vue')['default']
    LoadingIcon: typeof import('./src/components/loading/loading-icon.vue')['default']
    LoginButton: typeof import('./src/components/button/login-button.vue')['default']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    MenuItem: typeof import('./src/components/menu/menu-item.vue')['default']
    MessageBox: typeof import('./src/components/message/message-box.vue')['default']
    Pagination1: typeof import('./src/components/pagination/pagination-1.vue')['default']
    ResizeLayout: typeof import('./src/components/resize/resize-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialCard: typeof import('./src/components/card/social-card.vue')['default']
    SubmitIcon: typeof import('./src/components/icon/submit-icon.vue')['default']
    Tabbed: typeof import('./src/components/tabbed/tabbed.vue')['default']
    UploadButton: typeof import('./src/components/upload/upload-button.vue')['default']
    UploadDrawer: typeof import('./src/components/upload/upload-drawer.vue')['default']
    UploadTaskItem: typeof import('./src/components/upload/upload-task-item.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
