/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card/card.vue')['default']
    Card2: typeof import('./src/components/card/card-2.vue')['default']
    Checkbox1: typeof import('./src/components/checkbox/checkbox-1.vue')['default']
    CircleProgress: typeof import('./src/components/progress/circle-progress.vue')['default']
    CustomEditor: typeof import('./src/components/editor/custom-editor.vue')['default']
    Editor: typeof import('./src/components/editor/editor.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    Explorer: typeof import('./src/components/explorer/explorer.vue')['default']
    ExplorerRow: typeof import('./src/components/explorer/explorer-row.vue')['default']
    ExplorerRow2: typeof import('./src/components/explorer/explorer-row-2.vue')['default']
    FileItem: typeof import('./src/components/explorer/file-item.vue')['default']
    GlassCard: typeof import('./src/components/card/glass-card.vue')['default']
    LeftMenu: typeof import('./src/components/menu/left-menu.vue')['default']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    MenuItem: typeof import('./src/components/menu/menu-item.vue')['default']
    Pagination1: typeof import('./src/components/pagination/pagination-1.vue')['default']
    ResizeLayout: typeof import('./src/components/resize/resize-layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfCard: typeof import('./src/components/card/self-card.vue')['default']
    SocialCard: typeof import('./src/components/card/social-card.vue')['default']
    Tabbed: typeof import('./src/components/tabbed/tabbed.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
